name: CI Pipeline
on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev -y
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Build Linux
        run: ./build_linux.sh
      - name: Upload Zip
        uses: actions/upload-artifact@v1
        with:
          name: PoleVPN-linux.zip
          path: build/linux/PoleVPN.zip


  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Build Macos
        run: ./build_macos.sh
      - name: Upload Zip
        uses: actions/upload-artifact@v1
        with:
          name: PoleVPN-macos.zip
          path: build/macos/PoleVPN.zip
